### ISSUE TITLE
POST 500 (Internal Server Error)

### ISSUE THREAD

**Issue by SoxFace** [instructure/lti_tool_provider_example#3]
Hi guys, 

**Configuration type:**
By LTI 2 URL registration kicks up the following error:

common-39ad48f755.js:2 POST https://lti-tool-provider-example.herokuapp.com/register 500 (Internal Server Error)

Also, the URL in the site itself reads http. 

Can you let me know what I'm doing wrong?

Thanks

**Comment by augiethornton** [comment]
Hi SoxFace,

When you say the site itself; what site are you using exactly? Are you talking about the Heroku site that is hosting our LTI tool? If so, it depends on the protocol you're using to access the hosted tool i.e. http://lti-tool-provider-example.herokuapp.com/ will prepend the the LTI 2 example URL with the http protocol, as where if you used https it would prepend with the https protocol. 

You'll want to make sure to use https as your protocol identifier within your url for any LTI 2 registrations to avoid errors. If that still doesn't help resolve the issue you're seeing, please provide more details as to where/how you're attempting to register the Heroku hosted LTI 2 test tool.

**Comment by SoxFace** [comment]
Hey Augie, 

Thanks a million for your prompt response and time. Excuse my ignorance, I'm quite new to LTI. I've attached a GIF of exactly how I am adding the LTI Provider Example to Canvas. I am quite open to the idea that I am doing something silly, so please point out the obvious if I am.

![lti-provider-example](https://cloud.githubusercontent.com/assets/4454398/19369806/59517612-91f3-11e6-98a9-97260d246044.gif)

Looking forward to hearing from you.

Cheers
Sonya

**Comment by augiethornton** [comment]
Sonya,

Are you perhaps running Canvas on a web server that is not publicly accessible? LTI 2 registration process requires a callback to Canvas to finish the app install. If you are indeed running a local instance, try exposing your local web server through a public facing proxy server such as Ngrok or Localtunnel. That should handle the proxying of requests back to your local server from our publicly hosted LTI 2 test tool. Sorry it's not more verbose on the set up process.

Best

**Comment by SoxFace** [comment]
Nope - not running Canvas locally, it's a live https://uts.beta.instructure.com

**Comment by augiethornton** [comment]
Hey Sonya,

After further investigation into the issue it looks like a bug found its way into beta, which is causing the 500 error that you're seeing when attempting to register the LTI 2 Test Tool. I'll keep you in the loop when that issue gets fixed. We plan on taking care of it as soon as possible.

Thanks again for your patience.

**Comment by SoxFace** [comment]
Hi August,

The LTI2 example is now working, yay! However, my clone of the repo is not. 

I've gone through the commit history from 4 days ago and tried to replicate your changes.

Namely, adding assignment configuration placement for lib/canvas_extensions.rb

Is there something else I'm missing to get LTI2 up and running?

Cheers
Sonya

**Comment by augiethornton** [comment]
Hey Sonya,

We discovered that for some reason or another (currently investigating) that the Account setting "Beta and Test Access For Students" needs to be checked for the tool profile to load successfully. After selecting and saving this permission setting, you should be able to register the LTI 2 example tool without error. Let me know if that resolves the issue for you.

Best,
August

**Comment by SoxFace** [comment]
Awesome August, LTI2 is up and running on my clone. Many thanks for looking into it and keeping me posted. Really appreciate your time and sharing nature.

Cheers
Sonya
